version: '3.4'
services:

  #PHP Service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: backend-dev:1.3
    container_name: backend_app
    restart: unless-stopped
    tty: true
    ports:
      - "80:8080"
    working_dir: /www
    # volumes:
    #   - ./dev/nginx.conf:/etc/nginx/nginx.conf
    #   - ./dev/full.pem:/etc/nginx/full.pem
    #   - ./phplocal.ini:/etc/php/7.3/fpm/conf.d/50-setting.ini
    depends_on:
      - db
    networks:
      - backend_net
    env_file:
      - ../.env

  # Database
  db:
    image: postgres:14
    container_name: backend_db
    restart: always
    tty: true
    ports:
      - "5434:5432"
    volumes:
      - backend_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sail
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_app
    networks:
      - backend_net
    env_file:
      - ../.env

# Docker Networks
networks:
  backend_net:
    driver: bridge

# Docker Volumes
volumes:
  backend_db:
